### ISSUE TITLE
Can I use this to get  Lidl Plus receipts ? 

### ISSUE THREAD

**Issue by RocketRene** [Andre0512/lidl-plus#1]
Hi , thanks for open sourcing your work. 
I have some questions on how to use this script and what it can do ? 
Can you might give a small explanation how to use it 
Thanks

**Comment by Andre0512** [comment]
Hi, I committed my current state and created a readme.
I hope it's now more clear how to use it. :slightly_smiling_face:
Currently you can only fetch tickets/receipts, but I want to add more in the future.
