### ISSUE TITLE
API change

### ISSUE THREAD

**Issue by enteryournamehere** [Andre0512/lidl-plus#4]
Just letting you know that API version 1 became unavailable (at least here in NL), so I did some research, and here are the updated endpoints:

* Ticket list
Old: `https://tickets.lidlplus.com/api/v1/NL/tickets/list`
New: `https://tickets.lidlplus.com/api/v2/NL/tickets`
You can use the query parameter `pageNumber` to select the page of the paginated response, and `onlyFavorite` (true/false) to filter by favourite status.

* Ticket details
Old: `https://tickets.lidlplus.com/api/v1/NL/tickets/{id}`
New: `https://tickets.lidlplus.com/api/v2/NL/tickets/{id}`

Response data structure also slightly changed, for example `records` in the list response is now `tickets` instead.

Also, methods for these aren't currently implemented in your library, but you might be interested in them:
* Mark ticket (receipt) as favourite:
POST `https://tickets.lidlplus.com/api/v2/NL/tickets/favorite`, with JSON body `["ticketidhere"]`
* Mark ticket (receipt) as not favourite:
POST `https://tickets.lidlplus.com/api/v2/NL/tickets/unfavorite`, with JSON body `["ticketidhere"]`
* Coupon list: `https://coupons.lidlplus.com/api/v2/NL`
* Coupon details: `https://coupons.lidlplus.com/api/v2/NL/{id}`
* Coupon activation: POST (activate) or DELETE (deactivate) to `https://coupons.lidlplus.com/api/v1/NL/{id}/activation`

There's a bunch more endpoints for announcements, store details, shopping lists, etc, I'll document them all at some point, but hopefully the above will save you some trouble fixing the current methods in your library.

**Comment by Andre0512** [comment]
Hey, thanks for reporting and your research! 🙂
I'm on vacation until mid of next week. I will have a look then, or feel free to make a pr.

**Comment by enteryournamehere** [comment]
I don't actually have a use for this library myself, I just had to figure out the new API anyway for my own project, and wanted to share my findings with others who might be interested - so feel free to use or not use this info whenever you like :)
Enjoy your vacation!

**Comment by ahormann** [comment]
Thank you for the quick fix!
A note for other users: The keys in the resulting json changed for example an item now looks like this:
```
      "currentUnitPrice": "2,29",
      "quantity": "1",
      "isWeight": false,
      "originalAmount": "2,29",
      "name": "Mozarelli",
      "taxGroupName": "A",
      "codeInput": "4056489442431",
      "discounts": [],
      "deposit": null,
      "giftSerialNumber": null
```

**Comment by Andre0512** [comment]
I merged it and published a new release, thanks guys! 👍
@ahormann At first glance it looks the same, can you point out what changed? Pr of the readme are also welcome 🙂

**Comment by ahormann** [comment]
The description was renamed to name and the extendedAmount seems to be gone.

**Comment by Andre0512** [comment]
> The description was renamed to name and the extendedAmount seems to be gone.

Thanks, I updated the readme :+1:
